### ISSUE TITLE
CYCLER EVENT TODO LIST

### ISSUE THREAD

**Issue by FlavoredCactus** [FlavoredCactus/LLA-Station-13#2]
This is entirely subject to change but i just do not have the motivation to continue this project.
you can find the tree here:

https://github.com/FlavoredCactus/LLA-Station-13/tree/CYCLER_EVENTS

Events spread sheet can be found here https://docs.google.com/spreadsheets/d/1pWAQjulAu0aIbqekGyVZuRrztu7SFYNFJ9BuKzddHrk/edit#gid=0
(P) = pass
(F) = fail
(F/) = fail and round end
italics = not coded yet
bold = makes use of the EventStory() proc which is for setting up a end round story for people to read

- [ ] all comments in the code that include "//PLEASE RETURN TO THIS AFTER EVENT REWRITE" need to be rewritten as the events system was gutted to make this
- [ ] events need weight values for which ever event is more rare/more common
- [ ] minor events still need a boat load of pass fail events

I'm not entirely sure this is a complete list. you may ask me elsewhere for clarification. enjoy
